### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Perrytheplaty43** [Perrytheplaty43/Algorithms-and-Astronomy-Calculator#7]
- [x] Get app.js to test all files #8 
- [x] Add a date parameter and input to the astro target finder page
- [ ] Test the go algorithm with date parameter and expected result
- [ ] Remove `display: none` from astro css file and do it purely in js to prevent issues where the checkbox can start checked #11 
- [ ] Add NGC6341
- [ ] Add IC1369
